title: Charles Dardaman
email: charles@dardaman.com
description: >- # this means to ignore newlines until "baseurl:"
  Security | Hacking | Malware Analysis | OSCP | Reverse Engineering
baseurl: "/" # the subpath of your site, e.g. /blog
url: "dardaman.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: https://twitter.com/CharlesDardaman
github_username:  charlesdardaman

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-remote-theme


defaults:
  # _posts
  - scope:
      path: "/posts"
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
